import math
import datetime
import pandas_datareader as web
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense,LSTM
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
print('Enter the company code')
code = input()
print('Enter the start date')
startdate = input(datetime.date)
print('Enter the end date')
enddate = input(datetime.date)
df = web.DataReader(code,data_source='yahoo',start=startdate,end=enddate)
print("The Historical data of ",code)
print(df)
plt.figure(figsize=(12,7))
plt.title('Closing Price history')
plt.plot(df['Close'])
plt.xlabel('Date',fontsize = 18)
plt.ylabel('Closing price USD($)',fontsize = 18)
plt.show()
x= np.array(df.filter(['Low']))
y= np.array(df.filter(['Close']))
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma = 0.1)
svr_rbf.fit(x_train,y_train)
svm_confidence = svr_rbf.score(x_train,y_train)
print("The score of Support vector machine prediction")
print(svm_confidence)
lr = LinearRegression()
lr.fit(x_train,y_train)
lr_confidence = lr.score(x_train,y_train)
print("The score of Linear Regression prediction")
print(lr_confidence)
x_forecast = np.array(df.filter(['Close']))
lr_prediction = lr.predict(x_forecast)
print("the predicted values using linearregression")
lr_prediction = np.reshape(lr_prediction,(lr_prediction.shape[0],1))
print(lr_prediction)
svr_prediction = svr_rbf.predict(x_forecast)
print("the predicted values using support vector machine")
svr_prediction = np.reshape(svr_prediction,(svr_prediction.shape[0],1))
print(svr_prediction)
df = df.filter(['Close'])
data = df.filter(['Close'])
dataset = data.values
training_data_len = math.ceil(len(dataset*.8))
print(training_data_len)
scaler = MinMaxScaler(feature_range=(0,1))
scaled_data = scaler.fit_transform(dataset)
print("The scaled_data of the historical data")
print(scaled_data)
train_data = scaled_data[0:training_data_len,:]
x_train = []
y_train = []
for i in range(60,len(train_data)):
    x_train.append(train_data[i-60:i,0])
    y_train.append(train_data[i,0])
x_train,y_train = np.array(x_train),np.array(y_train)
x_train = np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))
x_train.shape
model = Sequential()
model.add(LSTM(50,return_sequences = True,input_shape = (x_train.shape[1],1)))
model.add(LSTM(50,return_sequences = False))
model.add(Dense(2))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')
print("The feedback cycles")
model.fit(x_train,y_train,batch_size=1,epochs=1)
print('Enter the start date for prediction')
stdate = input(datetime.date)
print('Enter the end date for prediction')
eddate = input(datetime.date)
apple = web.DataReader(code,data_source='yahoo',start=startdate,end=enddate)
new_df = apple.filter(['Close'])
last = new_df[-60:].values
last_scale = scaler.transform(last)
x_test = []
x_test.append(last_scale)
x_test = np.array(x_test)
x_test = np.reshape(x_test,(x_test.shape[0],x_test.shape[1],1))
predicted_price = model.predict(x_test)
predicted_price = scaler.inverse_transform(predicted_price)
print("The average predicted value during time period ")
print(predicted_price)
dates = apple.filter(['Low'])
prices= apple.filter(['Close'])
dates = np.reshape(dates,(dates.shape[0],1))
svr_lin = SVR(kernel = 'linear',C=1e3)
svr_poly = SVR(kernel = 'poly',C=1e3,degree=2)
svr_rbf = SVR(kernel = 'rbf',C=1e3,gamma=0.1)
svr_lin.fit(dates,prices)
svr_poly.fit(dates,prices)
svr_rbf.fit(dates,prices)
plt.figure(figsize=(14,7))
plt.scatter(dates,prices,color='black',label='Data')
plt.plot(dates,svr_rbf.predict(dates),color='red',label='RBF model')
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Predictions vs Data')
plt.legend()
plt.show()
plt.figure(figsize=(14,7))
plt.scatter(dates,prices,color='black',label='Data')
plt.plot(dates,svr_rbf.predict(dates),color='red',label='RBF model')
plt.plot(dates,svr_lin.predict(dates),color='green',label='linear model')
plt.plot(dates,svr_poly.predict(dates),color='blue',label='polynomial model')
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Predictions vs Data')
plt.legend()
plt.show()
